import { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import { Loader2, Music, Trophy, Calendar } from 'lucide-react';
import { GlassCard } from './GlassCard';
import { cn } from '../utils';
import { ActivityChart } from './ActivityChart';
import { ListeningClock } from './ListeningClock';
import { GenreBreakdown } from './GenreBreakdown';
import { TimeMachine } from './TimeMachine';
import { StreakCard } from './StreakCard';
import { DiversityScore } from './DiversityScore';
import { MainstreamScore } from './MainstreamScore';
import { ShareButton } from './ShareButton';

const API_URL = '/api';

export default function Stats({ username, onTrackClick }) {
    const [tracks, setTracks] = useState([]);
    const [loading, setLoading] = useState(false);
    const [period, setPeriod] = useState('overall'); // overall, 7day, 1month, 3month, 6month, 12month
    const [chartData, setChartData] = useState([]);
    const [clockData, setClockData] = useState([]);
    const [genreData, setGenreData] = useState([]);
    const [onThisDay, setOnThisDay] = useState([]);
    const [streak, setStreak] = useState(null);
    const [diversity, setDiversity] = useState(null);
    const [mainstream, setMainstream] = useState(null);
    const [topArtists, setTopArtists] = useState([]);

    const statsRef = useRef(null);


    const periods = [
        { value: 'overall', label: 'All Time' },
        { value: '7day', label: 'Last 7 Days' },
        { value: '1month', label: 'Last Month' },
        { value: '3month', label: 'Last 3 Months' },
        { value: '6month', label: 'Last 6 Months' },
        { value: '12month', label: 'Last Year' },
    ];

    useEffect(() => {
        if (username) {
            fetchTopTracks();
            fetchChartData();
        }
    }, [username, period]);

    const fetchTopTracks = async () => {
        setLoading(true);
        try {
            const response = await axios.get(`${API_URL}/stats/top-tracks/${username}`, {
                params: { period, limit: 50 },
            });
            setTracks(response.data);
        } catch (error) {
            console.error('Error fetching top tracks:', error);
        } finally {
            setLoading(false);
        }
    };


    const fetchChartData = async () => {
        try {
            // Fetch Activity Chart (1month default)
            const chartRes = await axios.get(`${API_URL}/stats/chart`, {
                params: { user: username, period: '1month' }
            });
            setChartData(chartRes.data);

            // Fetch Listening Clock (matches Top Tracks period)
            const clockRes = await axios.get(`${API_URL}/stats/listening-clock/${username}`, {
                params: { period }
            });
            setClockData(clockRes.data);

            // Fetch Genre Breakdown (matches Top Tracks period)
            const genreRes = await axios.get(`${API_URL}/stats/genre-breakdown/${username}`, {
                params: { period }
            });
            setGenreData(genreRes.data);

            // Fetch History features (independent of period selector, but we fetch on mount/user change)
            if (period === 'overall' || period === '1month') { // Only fetch once or when main view is active
                const otdRes = await axios.get(`${API_URL}/stats/on-this-day/${username}`);
                setOnThisDay(otdRes.data);

                const streakRes = await axios.get(`${API_URL}/stats/streak/${username}`);
                setStreak(streakRes.data.current_streak);

                const diversityRes = await axios.get(`${API_URL}/stats/diversity/${username}`, { params: { period } });
                setDiversity(diversityRes.data);

                const mainstreamRes = await axios.get(`${API_URL}/stats/mainstream/${username}`, { params: { period } });
                setMainstream(mainstreamRes.data);

                const artistsRes = await axios.get(`${API_URL}/stats/top-artists/${username}`, { params: { period: 'overall', limit: 3 } });
                setTopArtists(artistsRes.data);
            }

        } catch (error) {
            console.error('Error fetching stats:', error);
        }
    };

    return (
        <div ref={statsRef} className="space-y-6 pb-20 group group-[.capturing]:pb-6 group-[.capturing]:w-[800px] group-[.capturing]:mx-auto">
            {/* Capture Header */}
            <div className="hidden group-[.capturing]:block text-center mb-6">
                <h1 className="text-4xl font-bold text-white mb-2 tracking-tighter">My Spotify Stats</h1>
                <p className="text-spotify-grey text-sm uppercase tracking-widest mb-6">Generated by Spotiflow</p>

                {/* Capture-only Summary */}
                <div className="grid grid-cols-2 gap-8 mb-8 text-left max-w-2xl mx-auto">
                    <div>
                        <h3 className="text-spotify-green font-bold uppercase tracking-wider mb-2 text-sm">Top Artists</h3>
                        {topArtists.map((artist, i) => (
                            <div key={artist.name} className="flex items-center gap-2 mb-1">
                                <span className="text-spotify-grey font-mono text-xs">0{i + 1}</span>
                                <span className="font-semibold truncate">{artist.name}</span>
                            </div>
                        ))}
                    </div>
                    <div>
                        <h3 className="text-spotify-green font-bold uppercase tracking-wider mb-2 text-sm">Top Tracks</h3>
                        {tracks.slice(0, 3).map((track, i) => (
                            <div key={track.title} className="flex items-center gap-2 mb-1">
                                <span className="text-spotify-grey font-mono text-xs">0{i + 1}</span>
                                <div className="truncate">
                                    <span className="font-semibold">{track.title}</span>
                                    <span className="text-xs text-spotify-grey block">{track.artist}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Activity Chart */}
            <GlassCard className="p-6">
                <h3 className="text-lg font-semibold mb-4 text-spotify-grey uppercase tracking-wide">Last 30 Days Activity</h3>
                <ActivityChart data={chartData} />
            </GlassCard>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ListeningClock data={clockData} />
                <GenreBreakdown data={genreData} />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2">
                    <TimeMachine data={onThisDay} />
                </div>
                <div>
                    <StreakCard streak={streak} />
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <DiversityScore data={diversity} />
                <MainstreamScore data={mainstream} />
            </div>

            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 no-capture group-[.capturing]:hidden">

                <h2 className="text-xl font-semibold flex items-center gap-2">
                    <Trophy className="w-5 h-5 text-yellow-500" />
                    Top Tracks
                </h2>

                <div className="flex bg-black/10 dark:bg-white/10 p-1 rounded-full border border-black/5 dark:border-white/5 overflow-x-auto max-w-full">
                    {periods.map((p) => (
                        <button
                            key={p.value}
                            onClick={() => setPeriod(p.value)}
                            className={cn(
                                "px-3 py-1.5 rounded-full text-xs sm:text-sm font-medium transition-colors whitespace-nowrap",
                                period === p.value
                                    ? "bg-spotify-green text-white"
                                    : "text-gray-600 hover:text-black dark:text-gray-400 dark:hover:text-white"
                            )}
                        >
                            {p.label}
                        </button>
                    ))}
                </div>
            </div>

            {loading ? (
                <div className="flex justify-center py-20 no-capture group-[.capturing]:hidden">
                    <Loader2 className="w-10 h-10 animate-spin text-spotify-green" />
                </div>
            ) : (
                <div className="grid gap-3 no-capture group-[.capturing]:hidden">
                    <AnimatePresence mode="popLayout">
                        {tracks.map((track, index) => (
                            <GlassCard
                                key={`${track.title}-${track.artist}-${period}`}
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: 20 }}
                                transition={{ delay: index * 0.03 }}
                                image={track.image}
                                onClick={() => onTrackClick(track)}
                                className="p-3 flex items-center gap-4 group hover:bg-white/5 cursor-pointer"
                            >

                                <div className="flex-shrink-0 w-8 text-center font-bold text-spotify-grey group-hover:text-spotify-green transition-colors">
                                    #{track.rank}
                                </div>

                                <div className="flex-shrink-0 w-12 h-12 sm:w-16 sm:h-16 rounded-md overflow-hidden bg-black/20 relative">
                                    {track.image ? (
                                        <img src={track.image} alt={track.title} className="w-full h-full object-cover" />
                                    ) : (
                                        <div className="w-full h-full flex items-center justify-center">
                                            <Music className="w-6 h-6 text-spotify-grey" />
                                        </div>
                                    )}
                                </div>

                                <div className="flex-grow min-w-0">
                                    <h3 className="font-semibold text-base sm:text-lg truncate">{track.title}</h3>
                                    <p className="text-spotify-grey text-sm truncate">{track.artist}</p>
                                </div>

                                <div className="flex-shrink-0 text-right">
                                    <div className="font-bold text-spotify-green text-lg sm:text-xl">
                                        {track.playcount}
                                    </div>
                                    <div className="text-xs text-spotify-grey uppercase tracking-wide">
                                        Plays
                                    </div>
                                </div>
                            </GlassCard>
                        ))}
                    </AnimatePresence>

                    {tracks.length === 0 && !loading && (
                        <div className="text-center py-20 text-spotify-grey">
                            <Music className="w-16 h-16 mx-auto mb-4 opacity-50" />
                            <p>No plays found for this period.</p>
                        </div>
                    )}
                </div>
            )}

            <div className="no-capture group-[.capturing]:hidden">
                <ShareButton targetRef={statsRef} />
            </div>
        </div>
    );
}
